# Generated by Django 4.2.7 on 2023-12-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonModel',
        ),
    ]
