# Generated by Django 4.2.7 on 2024-11-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'PUBLISHED'), ('D', 'DRAFT')], default='P', max_length=20),
            preserve_default=False,
        ),
    ]
