# Generated by Django 4.2.7 on 2024-11-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
