# Generated by Django 4.2.7 on 2023-12-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='actor',
            new_name='employee',
        ),
    ]
