# Generated by Django 4.2.7 on 2023-12-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='author_id',
            new_name='author',
        ),
    ]
