# Generated by Django 4.2.7 on 2024-10-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
