# Generated by Django 4.2.7 on 2023-12-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
