# Generated by Django 4.2.7 on 2024-10-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_rename_cat_id_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWitoutRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
